name: CI

on:
  push:
  pull_request:

jobs:
  PHPUnit:
    name: PHPUnit (PHP ${{ matrix.php }})
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        php:
          - 8.5
          - 8.4
          - 8.3
          - 8.2
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
      - run: composer install
      - run: vendor/bin/phpunit --coverage-text
      - run: composer build
      - run: composer require symfony/console:^6.0 --dry-run --working-dir=tests/install-as-dep
      - run: composer require symfony/console:^7.0 --dry-run --working-dir=tests/install-as-dep
      - run: composer install --dry-run --working-dir=tests/install-as-dep
